server:
  port: 8080
  servlet:
    context-path: /api

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true


spring:
  application:
    name: management-api

  datasource:
    url: jdbc:postgresql://localhost:5432/management_db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
    continue-on-error: false

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: always

  security:
    user:
      name: admin
      password: admin
      roles: ADMIN

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME} #you can use environment variables or type here your configured email
    password: ${MAIL_PASSWORD} #you can use environment variables or type here your configured email application password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com
    default-encoding: UTF-8



logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
